# ----- GET ALL REQUESTS -----
GET http://localhost:3002/entries
###
GET http://localhost:3002/users

# ----- POST REQUESTS ------

###
POST http://localhost:3002/user/new 
Content-Type: application/json

{
    "_id": 5,
    "username": "Geordie",
    "calories": 2400,
    "protein": 130
}

###
POST http://localhost:3002/entry/new 
Content-Type: application/json

{
    "userId": 1,
    "entry": "food",
    "calories": 90,
    "protein": 10
}

# ----- GET (UPDATE) REQUESTS ---------

###
GET http://localhost:3002/entry/hide/6371858f33314bc9f3163780

###
GET http://localhost:3002/entries/1

###
GET http://localhost:3002/todays-entries/1

# ----- DELETE REQUESTS ------

###
DELETE http://localhost:3002/entry/delete/6371835f3dd20c4120c9dc88

###
DELETE http://localhost:3002/user/delete/4